name: task_manager_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
